package com.shounak.localmeshai.models

object ModelCatalog {
    val defaultModels = listOf(
        // ── ⭐ Recommended / Featured Local Models ────────────────────
        ModelInfo(
            id = "deepseek_r1_qwen15b_q8",
            name = "DeepSeek R1 Distill Qwen 1.5B ⭐ Highly Recommended",
            size = "1.86 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv1280.task",
            description = "⭐ Highly Recommended on-device model! Packaged as an Android MediaPipe .task model that loads weights into RAM/GPU and executes real local neural network inference with step-by-step reasoning.",
            backend = "MediaPipe LLM CPU-safe",
            deviceTarget = "8 GB nominal RAM, all supported chipsets",
            url = hf("litert-community/DeepSeek-R1-Distill-Qwen-1.5B", "DeepSeek-R1-Distill-Qwen-1.5B_multi-prefill-seq_q8_ekv1280.task"),
            modelPageUrl = "https://huggingface.co/litert-community/DeepSeek-R1-Distill-Qwen-1.5B",
            isRecommended = true,
            supportsThinkingMode = true
        ),
        ModelInfo(
            id = "gemma3n_e2b_vision",
            name = "Gemma 3n E2B 2B Vision ⭐ Recommended",
            size = "2.92 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Vision,
            fileName = "gemma-3n-E2B-it-int4.task",
            description = "⭐ Recommended Android-ready Gemma 3n 2B multimodal model for local image Q&A, visual detail analysis, and chat.",
            backend = "MediaPipe LLM Vision CPU-safe",
            deviceTarget = "8 GB RAM, all supported chipsets",
            url = hf("google/gemma-3n-E2B-it-litert-preview", "gemma-3n-E2B-it-int4.task"),
            modelPageUrl = "https://huggingface.co/google/gemma-3n-E2B-it-litert-preview",
            requiresHuggingFaceToken = true,
            isRecommended = true,
            contextWindowTokens = 32768
        ),
        ModelInfo(
            id = "qwen25_15b_gguf",
            name = "Qwen 2.5 1.5B (GGUF Q4_K_M) ⭐ Recommended",
            size = "1.1 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-1.5b-instruct-q4_k_m.gguf",
            description = "⭐ Recommended 4-bit quantized Qwen 2.5 1.5B GGUF model for fast, high-quality local reasoning and chat via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "6 GB+ RAM, all supported chipsets",
            url = hf("Qwen/Qwen2.5-1.5B-Instruct-GGUF", "qwen2.5-1.5b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 1_043_024_992L  // ~994 MB Q4_K_M
        ),
        ModelInfo(
            id = "qwen3_06b_litertlm",
            name = "Qwen 3 0.6B ⭐ Recommended",
            size = "586 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Qwen3-0.6B.litertlm",
            description = "⭐ Recommended lightweight Qwen 3 model for ultra-fast local reasoning, quick Q&A, and smooth step-by-step answers on any Android phone.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "8 GB nominal RAM, all supported chipsets",
            url = hf("litert-community/Qwen3-0.6B", "Qwen3-0.6B.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Qwen3-0.6B",
            isRecommended = true,
            contextWindowTokens = 4096
        ),
        ModelInfo(
            id = "gemma3_1b_recommended",
            name = "Gemma 3 1B IT ⭐ Recommended",
            size = "555 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "gemma3-1b-it-int4.task",
            description = "⭐ Recommended small Gemma starter model for fast questions, short summaries, and quick on-device chat.",
            backend = "LiteRT-LM Conversation (CPU)",
            deviceTarget = "8 GB RAM, all supported chipsets",
            url = hf("litert-community/Gemma3-1B-IT", "gemma3-1b-it-int4.task"),
            modelPageUrl = "https://huggingface.co/litert-community/Gemma3-1B-IT",
            requiresHuggingFaceToken = true,
            isRecommended = true,
            contextWindowTokens = 2048
        ),
        ModelInfo(
            id = "safetensors_conversion_info",
            name = "Safetensors Guide 💡",
            size = "N/A",
            status = ModelStatus.ComingSoon,
            type = ModelType.Text,
            fileName = "model.safetensors",
            description = "Raw .safetensors (PyTorch FP16/BF16) checkpoints exceed mobile RAM limits. Download corresponding pre-quantized .gguf or .litertlm models above for on-device chat.",
            backend = "Needs GGUF / LiteRT conversion",
            deviceTarget = "Conversion guidance"
        ),

        // ── Coding specialists ────────────────────────────────────────
        ModelInfo(
            id = "qwen25_coder_15b_gguf",
            name = "Qwen 2.5 Coder 1.5B (GGUF Q4_K_M) ⌨️",
            size = "1.1 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-coder-1.5b-instruct-q4_k_m.gguf",
            description = "Lightweight coding specialist for code generation, bug fixing, and syntax explanations running via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "6 GB nominal RAM, all supported chipsets",
            url = hf("Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF", "qwen2.5-coder-1.5b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/Qwen/Qwen2.5-Coder-1.5B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 1_043_220_640L  // ~994 MB Coder Q4_K_M
        ),
        ModelInfo(
            id = "qwen25_coder_3b_litertlm",
            name = "Qwen 2.5 Coder 3B ⌨️",
            size = "2.91 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-coder-3b.litertlm",
            description = "Higher-quality coding model for Android, Python, project reasoning, and longer technical explanations. Choose it over the 1.5B coder model when accuracy matters more than speed or memory use.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "12 GB RAM recommended",
            url = hf("4ntoine/Qwen2.5-Coder-3B-Instruct-LiteRTLM", "model.litertlm"),
            modelPageUrl = "https://huggingface.co/4ntoine/Qwen2.5-Coder-3B-Instruct-LiteRTLM"
        ),

        // ── Qwen family ──────────────────────────────────────────────
        ModelInfo(
            id = "qwen25_05b_gguf",
            name = "Qwen 2.5 0.5B (GGUF Q4_K_M)",
            size = "398 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-0.5b-instruct-q4_k_m.gguf",
            description = "Ultra-compact 0.5B Qwen model for lightning fast responses and low-memory devices via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "4 GB nominal RAM, all supported chipsets",
            url = hf("Qwen/Qwen2.5-0.5B-Instruct-GGUF", "qwen2.5-0.5b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 397_206_688L  // Q4_K_M ~379 MB actual
        ),
        ModelInfo(
            id = "qwen3_17b_litertlm",
            name = "Qwen 3 1.7B",
            size = "2.1 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Qwen3_1.7B.litertlm",
            description = "Small Qwen 3 reasoning model between 0.6B and 4B, useful for general chat with better step-by-step ability than the tiny build. This public LiteRT-LM artifact is ready for direct download.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "8 GB nominal RAM",
            url = hf("litert-community/Qwen3-1.7B", "Qwen3_1.7B.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Qwen3-1.7B",
            requiresHuggingFaceToken = false
        ),
        ModelInfo(
            id = "qwen25_3b_gguf",
            name = "Qwen 2.5 3B (GGUF Q4_K_M)",
            size = "2.0 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-3b-instruct-q4_k_m.gguf",
            description = "High-performing 3B Qwen chat model with great reasoning and instruction following via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "8 GB nominal RAM",
            url = hf("Qwen/Qwen2.5-3B-Instruct-GGUF", "qwen2.5-3b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 1_934_769_504L  // ~1.80 GB Q4_K_M
        ),
        ModelInfo(
            id = "qwen25_7b_gguf",
            name = "Qwen 2.5 7B Instruct (GGUF Q4_K_M)",
            size = "4.68 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen2.5-7b-instruct-q4_k_m.gguf",
            description = "High-quality Qwen 2.5 7B instruction model running locally on-device via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "12–16 GB RAM recommended",
            url = hf("Qwen/Qwen2.5-7B-Instruct-GGUF", "qwen2.5-7b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/Qwen/Qwen2.5-7B-Instruct-GGUF",
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 4_685_135_072L  // ~4.36 GB Q4_K_M
        ),
        ModelInfo(
            id = "qwen3_4b_litertlm",
            name = "Qwen 3 4B Reasoning",
            size = "5.3 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen3_4b_channelwise_int8_float32kv.litertlm",
            description = "Qwen 3 reasoning model for math, planning, structured answers, and step-by-step problem solving. It needs much more memory and a high-end LiteRT-LM GPU profile than the smaller Qwen options.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "12 GB RAM recommended",
            url = hf("litert-community/Qwen3-4B", "qwen3_4b_channelwise_int8_float32kv.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Qwen3-4B"
        ),
        ModelInfo(
            id = "qwen3_8b_litertlm",
            name = "Qwen 3 8B Reasoning",
            size = "7.7 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen3_8b_channelwise_int8_float32kv.litertlm",
            description = "Large Qwen 3 reasoning model for the strongest local answers in the current Qwen 3 LiteRT-LM set. Use it only on phones with enough RAM and a verified high-end chipset, because initialization and generation are demanding.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "16 GB RAM recommended",
            url = hf("litert-community/Qwen3-8B", "qwen3_8b_channelwise_int8_float32kv.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Qwen3-8B"
        ),
        ModelInfo(
            id = "qwen3_14b_litertlm",
            name = "Qwen 3 14B",
            size = "8.66 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "qwen3_14b_mixed_int4.litertlm",
            description = "Large dense Qwen 3 reasoning model using a mixed INT4 LiteRT-LM artifact for high-quality local answers. It is a strongest-phones-only option because download size, RAM pressure, and initialization risk are high.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "16 GB RAM, strongest phones only",
            url = hf("litert-community/Qwen3-14B", "qwen3_14b_mixed_int4.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Qwen3-14B"
        ),

        // ── Llama family ─────────────────────────────────────────────
        ModelInfo(
            id = "llama32_1b_gguf",
            name = "Llama 3.2 1B Instruct (GGUF Q4_K_M)",
            size = "750 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Llama-3.2-1B-Instruct-Q4_K_M.gguf",
            description = "Fast, efficient 1.2B parameter Llama 3.2 model running locally via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "6 GB nominal RAM, all supported chipsets",
            url = hf("bartowski/Llama-3.2-1B-Instruct-GGUF", "Llama-3.2-1B-Instruct-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            // Exact size from bartowski HF repo — label "750 MB" is approximate.
            // Q4_0 variant is ~718 MB; if local file is ~718 MB, it is the wrong artifact.
            expectedFileSizeBytes = 770_303_744L
        ),
        ModelInfo(
            id = "llama32_3b_gguf",
            name = "Llama 3.2 3B Instruct (GGUF Q4_K_M)",
            size = "2.0 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Llama-3.2-3B-Instruct-Q4_K_M.gguf",
            description = "High quality 3.2B parameter Llama 3.2 model running locally via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "8 GB nominal RAM",
            url = hf("bartowski/Llama-3.2-3B-Instruct-GGUF", "Llama-3.2-3B-Instruct-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 2_019_377_984L  // ~1.88 GB Q4_K_M
        ),
        ModelInfo(
            id = "llama31_8b_gguf",
            name = "Llama 3.1 8B Instruct (GGUF Q4_K_M)",
            size = "4.92 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf",
            description = "Strong Llama 3.1 8B instruction model running locally on-device via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "12–16 GB RAM recommended",
            url = hf("bartowski/Meta-Llama-3.1-8B-Instruct-GGUF", "Meta-Llama-3.1-8B-Instruct-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF",
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 4_920_738_944L  // ~4.58 GB Q4_K_M
        ),

        // ── Mistral family ───────────────────────────────────────────
        ModelInfo(
            id = "mistral_7b_gguf",
            name = "Mistral 7B Instruct v0.3 (GGUF Q4_K_M)",
            size = "4.37 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Mistral-7B-Instruct-v0.3-Q4_K_M.gguf",
            description = "Mistral 7B Instruct v0.3 model running locally on-device via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "12–16 GB RAM recommended",
            url = hf("bartowski/Mistral-7B-Instruct-v0.3-GGUF", "Mistral-7B-Instruct-v0.3-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF",
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 4_368_439_456L  // ~4.07 GB Q4_K_M
        ),
        ModelInfo(
            id = "mistral_ministral_8b_candidate",
            name = "Mistral Ministral 8B Instruct",
            size = "~8 GB (est.)",
            status = ModelStatus.NeedsConversion,
            type = ModelType.Text,
            fileName = "ministral-8b-instruct.litertlm",
            description = "Ministral 8B is a stronger Mistral-family chat model for richer answers, summaries, and reasoning. This card is a future-build placeholder until a compatible Android artifact exists.",
            backend = "Conversion needed",
            deviceTarget = "16 GB RAM, needs Android GPU artifact",
            modelPageUrl = "https://huggingface.co/mistralai/Ministral-8B-Instruct-2410"
        ),

        // ── Phi family ───────────────────────────────────────────────
        ModelInfo(
            id = "phi35_mini_gguf",
            name = "Phi 3.5 Mini Instruct (GGUF Q4_K_M)",
            size = "2.2 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Phi-3.5-mini-instruct-Q4_K_M.gguf",
            description = "Microsoft Phi 3.5 Mini instruction model with strong reasoning ability running via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "8 GB nominal RAM",
            url = hf("bartowski/Phi-3.5-mini-instruct-GGUF", "Phi-3.5-mini-instruct-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/Phi-3.5-mini-instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 2_176_116_064L  // ~2.03 GB Q4_K_M
        ),
        ModelInfo(
            id = "phi4_mini_mediapipe",
            name = "Phi 4 Mini Instruct - MediaPipe",
            size = "3.9 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Phi-4-mini-instruct_multi-prefill-seq_q8_ekv1280.task",
            description = "Android-ready Phi 4 Mini text model using the CPU-safe MediaPipe LLM runtime. It is good for chat, writing, and explanations, but this bundle is text-only and does not include audio encoders.",
            backend = "MediaPipe LLM CPU-safe",
            deviceTarget = "12 GB RAM recommended",
            url = hf("litert-community/Phi-4-mini-instruct", "Phi-4-mini-instruct_multi-prefill-seq_q8_ekv1280.task"),
            modelPageUrl = "https://huggingface.co/litert-community/Phi-4-mini-instruct",
            isRecommended = true
        ),
        ModelInfo(
            id = "phi4_mini_reasoning_litertlm",
            name = "Phi 4 Mini Reasoning",
            size = "~3.8 GB (est.)",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "Phi-4-mini-reasoning.litertlm",
            description = "Reasoning-tuned Phi 4 Mini variant for math, logic, planning, and step-by-step explanations. It is heavier than ordinary small chat models and uses LiteRT-LM GPU, so device compatibility matters.",
            backend = "LiteRT-LM GPU",
            deviceTarget = "12 GB RAM recommended",
            url = hf("litert-community/Phi-4-mini-reasoning", "Phi-4-mini-reasoning.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/Phi-4-mini-reasoning"
        ),

        // ── DeepSeek family ──────────────────────────────────────────
        ModelInfo(
            id = "deepseek_r1_qwen7b_gguf",
            name = "DeepSeek R1 Distill Qwen 7B (GGUF Q4_K_M)",
            size = "4.68 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf",
            description = "Larger DeepSeek R1 distill for stronger math, logic, and structured step-by-step reasoning running locally on-device via llama.cpp JNI backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "12–16 GB RAM recommended",
            url = hf("unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF", "DeepSeek-R1-Distill-Qwen-7B-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/unsloth/DeepSeek-R1-Distill-Qwen-7B-GGUF",
            supportsThinkingMode = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 4_683_272_352L  // ~4.36 GB Q4_K_M
        ),

        // ── Compact & Ultra-light models ──────────────────────────────
        ModelInfo(
            id = "smollm2_135m_gguf",
            name = "SmolLM2 135M Instruct (GGUF Q4_K_M) ⚡",
            size = "95 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "smollm2-135m-instruct-q4_k_m.gguf",
            description = "Ultra-small 135M model from Hugging Face for instant responses on any device with minimal RAM.",
            backend = "llama.cpp GGUF",
            deviceTarget = "4 GB RAM, all devices",
            url = hf("HuggingFaceTB/SmolLM2-135M-Instruct-GGUF", "smollm2-135m-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/HuggingFaceTB/SmolLM2-135M-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 2048,
            expectedFileSizeBytes = 94_624_352L   // ~90 MB Q4_K_M
        ),
        ModelInfo(
            id = "smollm2_360m_gguf",
            name = "SmolLM2 360M Instruct (GGUF Q4_K_M) ⚡",
            size = "230 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "smollm2-360m-instruct-q4_k_m.gguf",
            description = "Compact 360M parameter model with impressive general chat and reasoning for its size.",
            backend = "llama.cpp GGUF",
            deviceTarget = "4 GB RAM, all devices",
            url = hf("HuggingFaceTB/SmolLM2-360M-Instruct-GGUF", "smollm2-360m-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/HuggingFaceTB/SmolLM2-360M-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 2048,
            expectedFileSizeBytes = 228_691_136L  // ~218 MB Q4_K_M
        ),
        ModelInfo(
            id = "tinyllama_11b_gguf",
            name = "TinyLlama 1.1B Chat (GGUF Q4_K_M)",
            size = "669 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf",
            description = "Lightweight 1.1B chat model running via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "4 GB+ RAM, all devices",
            url = hf("TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF", "tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF",
            isRecommended = true,
            contextWindowTokens = 2048,
            expectedFileSizeBytes = 668_916_736L  // ~638 MB Q4_K_M
        ),
        ModelInfo(
            id = "smollm2_17b_gguf",
            name = "SmolLM2 1.7B Instruct (GGUF Q4_K_M)",
            size = "1.05 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "smollm2-1.7b-instruct-q4_k_m.gguf",
            description = "Powerful 1.7B parameter instruction model offering great knowledge and chat capability.",
            backend = "llama.cpp GGUF",
            deviceTarget = "6 GB nominal RAM",
            url = hf("HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF", "smollm2-1.7b-instruct-q4_k_m.gguf"),
            modelPageUrl = "https://huggingface.co/HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 1_039_847_040L // ~991 MB Q4_K_M
        ),
        ModelInfo(
            id = "gemma2_2b_gguf",
            name = "Gemma 2 2B IT (GGUF Q4_K_M)",
            size = "1.6 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "gemma-2-2b-it-Q4_K_M.gguf",
            description = "Google Gemma 2 2B instruction model running locally via native llama.cpp backend.",
            backend = "llama.cpp GGUF",
            deviceTarget = "6 GB nominal RAM",
            url = hf("bartowski/gemma-2-2b-it-GGUF", "gemma-2-2b-it-Q4_K_M.gguf"),
            modelPageUrl = "https://huggingface.co/bartowski/gemma-2-2b-it-GGUF",
            isRecommended = true,
            contextWindowTokens = 4096,
            expectedFileSizeBytes = 1_631_906_176L  // ~1.52 GB Q4_K_M
        ),
        ModelInfo(
            id = "gemma3_270m_q8",
            name = "Gemma 3 270M",
            size = "304 MB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "gemma3-270m-it-q8.task",
            description = "Tiny Gemma 3 instruction model for quick tests, short answers, and low-memory local chat. Its task bundle runs through LiteRT-LM's native conversation layer; the Google Gemma license and a Hugging Face read token are required.",
            backend = "LiteRT-LM Conversation (CPU)",
            deviceTarget = "8 GB RAM, all supported chipsets",
            url = hf("litert-community/gemma-3-270m-it", "gemma3-270m-it-q8.task"),
            modelPageUrl = "https://huggingface.co/litert-community/gemma-3-270m-it",
            requiresHuggingFaceToken = true
        ),
        ModelInfo(
            id = "gemma3_4b_q8",
            name = "Gemma 3 4B IT",
            size = "~3.4 GB (est.)",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Text,
            fileName = "gemma3-4b-it-int4.task",
            description = "Mid-size Gemma 3 instruction-tuned model for stronger chat, writing, and reasoning than the 270M or 1B variants. Its Android task package runs through LiteRT-LM's conversation layer and requires the Google Gemma license plus a Hugging Face read token.",
            backend = "LiteRT-LM Conversation (CPU)",
            deviceTarget = "12 GB RAM recommended",
            url = hf("litert-community/Gemma3-4B-IT", "gemma3-4b-it-int4.task"),
            modelPageUrl = "https://huggingface.co/litert-community/Gemma3-4B-IT",
            requiresHuggingFaceToken = true
        ),

        // ── Vision / Image Q&A models ────────────────────────────────
        ModelInfo(
            id = "fastvlm_05b_litertlm",
            name = "FastVLM 0.5B",
            size = "1.08 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Vision,
            fileName = "FastVLM-0.5B.litertlm",
            description = "FastVLM 0.5B is a lightweight vision-language model for quick image descriptions and simple visual questions. It is smaller than Gemma vision models, but the LiteRT-LM vision runtime still depends on device GPU compatibility.",
            backend = "LiteRT-LM Vision GPU",
            deviceTarget = "8 GB nominal RAM",
            url = hf("litert-community/FastVLM-0.5B", "FastVLM-0.5B.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/FastVLM-0.5B",
            contextWindowTokens = 1280
        ),
        ModelInfo(
            id = "gemma4_e2b_litertlm",
            name = "Gemma 4 E2B IT",
            size = "2.14 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Vision,
            fileName = "gemma-4-E2B-it.litertlm",
            description = "Gemma 4 E2B is a compact LiteRT-LM multimodal package for text, image, and audio-capable chats when the bundle includes the needed encoders. It should be used only on verified high-end LiteRT-LM device profiles; use MediaPipe vision models on mid-range phones.",
            backend = "LiteRT-LM multimodal CPU/GPU",
            deviceTarget = "Flagship LiteRT-LM GPU chipset recommended",
            url = hf("litert-community/gemma-4-E2B-it-litert-lm", "gemma-4-E2B-it.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm",
            supportsAudioInput = true,
            supportsThinkingMode = true,
            contextWindowTokens = 32768
        ),
        ModelInfo(
            id = "gemma4_e4b_litertlm",
            name = "Gemma 4 E4B IT",
            size = "3.41 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Vision,
            fileName = "gemma-4-E4B-it.litertlm",
            description = "Gemma 4 E4B is a stronger LiteRT-LM multimodal model for richer image and text answers, with audio support only when the bundle includes the required encoders. It is heavier than E2B and should be treated as high-end-phone-only unless the crash guard proves it works.",
            backend = "LiteRT-LM multimodal CPU/GPU",
            deviceTarget = "12 GB RAM recommended",
            url = hf("litert-community/gemma-4-E4B-it-litert-lm", "gemma-4-E4B-it.litertlm"),
            modelPageUrl = "https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm",
            supportsAudioInput = true,
            supportsThinkingMode = true,
            contextWindowTokens = 32768
        ),
        ModelInfo(
            id = "gemma3n_e4b_vision",
            name = "Gemma 3n E4B Vision",
            size = "4.10 GB",
            status = ModelStatus.NotDownloaded,
            type = ModelType.Vision,
            fileName = "gemma-3n-E4B-it-int4.task",
            description = "Gemma 3n E4B Vision is the stronger Gemma 3n image Q&A option for more detailed visual reasoning and richer image descriptions. It needs more memory than E2B and requires the Google Gemma license plus a Hugging Face read token.",
            backend = "MediaPipe LLM Vision CPU-safe",
            deviceTarget = "12 GB RAM recommended",
            url = hf("google/gemma-3n-E4B-it-litert-preview", "gemma-3n-E4B-it-int4.task"),
            modelPageUrl = "https://huggingface.co/google/gemma-3n-E4B-it-litert-preview",
            requiresHuggingFaceToken = true,
            contextWindowTokens = 32768
        )
    )

    private fun hf(repo: String, file: String): String {
        return "https://huggingface.co/$repo/resolve/main/$file?download=true"
    }
}
